# Generated by Django 5.1.1 on 2024-09-24 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionApp', '0001_initial'),
        ('users', '0003_trainer_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meals',
            new_name='Meal',
        ),
    ]
