# Generated by Django 5.1.1 on 2024-09-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionApp', '0002_rename_meals_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='servingSize',
            field=models.CharField(default='1 egg', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='food',
            name='fats',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
