# Generated by Django 5.1.1 on 2024-09-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionApp', '0003_food_servingsize_alter_food_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='servings',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
