# Generated by Django 5.1.1 on 2024-09-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionApp', '0004_alter_food_servings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='servings',
        ),
    ]
