# Generated by Django 5.1.1 on 2024-09-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutApp', '0002_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='is_restDay',
            field=models.BooleanField(default=True),
        ),
    ]
